name: toss_flutter
description: "toss clone coding"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  freezed_annotation: ^3.1.0
  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  retrofit: ^4.9.1
  logger: ^2.6.2
  json_annotation: ^4.9.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.7.1
  retrofit_generator: ^10.0.0
  json_serializable: ^6.11.2
  freezed: ^3.2.3

flutter:
  uses-material-design: true
